"""autogenerated by alembic

Revision ID: 17556c379ceb
Revises: 3cd09cd2181f
Create Date: 2025-03-21 18:54:11.776988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17556c379ceb'
down_revision = '3cd09cd2181f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
